package com.test.money.transfer.model;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Account of the client. Client Id and currency Id must be unique (database constraint).
 */
@Data
public class Account implements Serializable {

    /**
     * Id client in database (auto generated by the database).
     */
    private Integer id;
    /**
     * Ownewr of the account.
     */
    private Client client;
    /**
     * Currency of the account.
     */
    private Currency currency;
    /**
     * Balance of the account.
     */
    private BigDecimal balance;

}
