package com.test.money.transfer.model;

import lombok.Data;

import java.io.Serializable;

/**
 * Client. Email must be unique (database constraint).
 */
@Data
public class Client implements Serializable {

  /**
   * Id client in database (auto generated by the database).
   */
  private Integer id;
  /**
   * Name of the client.
   */
  private String name;
  /**
   * Email of the client.
   */
  private String email;
}
