package com.test.money.transfer.model;

import lombok.Data;

/**
 * Currency. Code must be unique (database constraint).
 */
@Data
public class Currency {

  /**
   * Id client in database (auto generated by the database)
   */
  private Integer id;
  /**
   * Code of the currency (USD, EUR, etc).
   */
  private String code;
}
