package com.test.money.transfer.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Contains information about the transaction.
 */
@Data
public class Transfer implements Serializable {

  /**
   * Id client in database (auto generated by the database)
   */
  private Integer id;
  /**
   * Account from where the money  is transferred
   */
  private Account from;
  /**
   * Account where the money  is transferred
   */
  private Account to;
  /**
   * Transfer amount
   */
  private BigDecimal amount;
  /**
   * Date with time of the transfer
   */
  private LocalDateTime date;
  /**
   * Is transfer finished or not
   */
  private boolean finished = false;
}
