drop table if exists clients;
create table clients (
    client_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    client_name varchar(50) not null,
    email varchar(50) UNIQUE not null
);

create table accounts (
    account_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    client_id INTEGER not null,
    currency varchar(5) not null,
    balance DECIMAL(10,2) DEFAULT 0.00,
    FOREIGN KEY (client_id) REFERENCES clients(client_id)
);