drop table if exists clients;
create table clients (
    client_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    first_name varchar(50) not null,
    last_name varchar(50) not null
);